import GraButton from "@/components/common/Buttons";
import Image from "next/image";
import { useEffect, useState } from "react";
import { toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import React from "react";

import Button from "@mui/material/Button";
import Dialog from "@mui/material/Dialog";
import DialogActions from "@mui/material/DialogActions";
import DialogContent from "@mui/material/DialogContent";
import DialogContentText from "@mui/material/DialogContentText";
import DialogTitle from "@mui/material/DialogTitle";
import TextField from "@mui/material/TextField";
import InputAdornment from "@mui/material/InputAdornment";
import Head from "next/head";
const Boosted = () => {
  const [eth, setEth] = useState("");
  const [usdt, setUsdt] = useState("");

  const [depositAmount, setDepositAmount] = useState<number>();

  const [openClaim, setOpenClaim] = React.useState(false);


  const handleClose = () => {
    setOpenClaim(false);
  };
  const handleChange = (event) => {
    if (event.target.value < 0) return;
    setDepositAmount(event.target.value);
  };
  const getCurrentPool = async () => {
   
  };
  const getYZBalance = async () => {
    
  };
  const getStakedAmount = async () => {
    
  };
  const getPendingReward = async () => {
    
  };
  const onClaim = async () => {
    
  };
  return (
    <>
      <Head>
        <title>Boost APY</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <div className="flex justify-center mt-[55px] align-middle border-[1px] bg-[#1C1C1C]/[.6]  border-white/10 backdrop-blur-md rounded-2xl p-[20px] mb-10 max-w-[915px] md:px-[85px] px-[20px] pb-[46px] m-auto">
        <div className="w-[100%] pt-6">
          {/* Page title */}
          <h2 className="text-white text-[32px] font-bold px-3">Boost APY</h2>
          <div className="">
            <div className="p-[8px] w-[100%]">
              {/* Current Pool Card Started */}
              <div className="relative pt-0 pb-[21px] border-[1px] rounded-xl bg-white/5 mdh-[120px] border-white/10 max-md:w-[100%] max-md:mx-0 box-border h-[30%]">
                <div className="bg-white/5 border-b-[1px] border-white/10 rounded-xl flex w-full h-[43px] align-middle pl-4">

                  <h4 className="text-white font-semibold text-[20px] m-auto">
                    Current STAKED NFTs
                  </h4>

                </div>
              </div>
            </div>
          </div>
        </div>
      </div>{" "}
      {/* Claim */}
      <Dialog
        onClose={handleClose}
        open={openClaim}
        aria-labelledby="alert-dialog-title"
        aria-describedby="alert-dialog-description"
        sx={{ backdropFilter: "blur(5px)" }}
        maxWidth="xs"
      >
        <DialogTitle
          sx={{
            display: "flex",
            justifyContent: "center",
            color: "#7f16ba",
            bgcolor: "#e8aef7",
          }}
        >
          Claim Lock Time
        </DialogTitle>
        <DialogContent
          sx={{
            display: "block",
            bgcolor: "#e8aef7",
          }}
        >
          <div className="flex justify-center">
            <TextField
              label="Time Lock:"
              id="outlined-start-adornment"
              sx={{ m: 1, width: "25ch" }}
              defaultValue="12 Hours"
              InputProps={{
                readOnly: true,
                startAdornment: (
                  <InputAdornment position="start">YZ</InputAdornment>
                ),
              }}
            />
          </div>

          <DialogContentText
            id="alert-dialog-description"
            sx={{
              display: "flex",
              justifyContent: "center",
              color: "#7f16ba",
              textAlign: "center",
            }}
          >
            The lock period is not over ! Once it has expired, you can claim the
            rewards you have earned so far.
          </DialogContentText>
        </DialogContent>
        <DialogActions
          sx={{
            display: "flex",
            justifyContent: "center",
            bgcolor: "#e8aef7",
          }}
        >
          <Button onClick={handleClose} sx={{ color: "#7f16ba" }}>
            Confirm
          </Button>
        </DialogActions>
      </Dialog>
    </>
  );
};

export default Boosted;
