import { useEffect } from "react";
import Image from "next/image";

import Head from "next/head";

const Dashboard = () => {

  useEffect(() => {
    getDashboardInfo();
  }, []);

  const getDashboardInfo = async () => {
   
  };

  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <div className="grow min-[1144px]:flex justify-center w-[100%] mt-[55px] pb-[40px]">
        <div className="min-[1144px]:w-[69%] pb-[20px] mr-[10px] ">
          <div className="align-middle border-[1px] bg-[#1C1C1C]/[.6]  border-white/10 backdrop-blur-md rounded-2xl">
            {/* Current Statistic Started */}

            <div className="justify-around pt-6 pb-[21px] m-2">
              <div className="flex flex-row py-3">
                <div className="align-middle border-[1px] rounded-lg bg-white/5  border-white/10 my-auto w-[60px] h-[60px] flex">
                  <Image
                    className="z-[-9999] top-0 right-0 m-auto"
                    src="./icon/totalsupply.svg"
                    alt="slider pannel"
                    width={32}
                    height={32}
                  />
                </div>
                <div className="m-auto ml-2">
                  <h4 className="text-white text-[20px] m-auto">
                    Total staked VPUMPY Token 
                  </h4>
                  <h4 className="text-white font-semibold uppercase text-[24px] m-auto">
                    {/* {totalSupply} $YZ */}
                    0
                  </h4>
                </div>
              </div>
              <div className="flex flex-row py-3">
                <div className="align-middle border-[1px] rounded-lg bg-white/5  border-white/10 my-auto w-[60px] h-[60px] flex">
                  <Image
                    className="z-[-9999] top-0 right-0 m-auto"
                    src="./icon/Locked $YZ.svg"
                    alt="slider pannel"
                    width={32}
                    height={32}
                  />
                </div>
                <div className="m-auto ml-2">
                  <h4 className="text-white text-[20px] m-auto">
                    Total staked VPUMPY NFT 1
                  </h4>
                  <h4 className="text-white font-semibold uppercase text-[24px] m-auto">
                    {/* {lockYieldz} $VP */} {"0"}
                  </h4>
                </div>
              </div>
              <div className="flex flex-row py-3">
                <div className="align-middle border-[1px] rounded-lg bg-white/5  border-white/10 my-auto w-[60px] h-[60px] flex">
                  <Image
                    className="z-[-9999] top-0 right-0 m-auto"
                    src="./icon/Market Cap.svg"
                    alt="slider pannel"
                    width={32}
                    height={32}
                  />
                </div>
                <div className="m-auto ml-2">
                  <h4 className="text-white text-[20px] m-auto">Total staked VPUMPY NFT 2</h4>
                  <h4 className="text-white font-semibold uppercase text-[24px] m-auto">
                    {"0"}
                  </h4>
                </div>
              </div>
              <div className="flex flex-row py-3">
                <div className="align-middle border-[1px] rounded-lg bg-white/5  border-white/10 my-auto w-[60px] h-[60px] flex">
                  <Image
                    className="z-[-9999] top-0 right-0 m-auto"
                    src="./icon/totalsupply.svg"
                    alt="slider pannel"
                    width={32}
                    height={32}
                  />
                </div>
                <div className="m-auto ml-2">
                  <h4 className="text-white text-[20px] m-auto">
                    My staked VPUMPY Token 
                  </h4>
                  <h4 className="text-white font-semibold uppercase text-[24px] m-auto">
                    {/* {totalSupply} $YZ */}
                    0
                  </h4>
                </div>
              </div>
              <div className="flex flex-row py-3">
                <div className="align-middle border-[1px] rounded-lg bg-white/5  border-white/10 my-auto w-[60px] h-[60px] flex">
                  <Image
                    className="z-[-9999] top-0 right-0 m-auto"
                    src="./icon/Locked $YZ.svg"
                    alt="slider pannel"
                    width={32}
                    height={32}
                  />
                </div>
                <div className="m-auto ml-2">
                  <h4 className="text-white text-[20px] m-auto">
                    My staked VPUMPY NFT 1
                  </h4>
                  <h4 className="text-white font-semibold uppercase text-[24px] m-auto">
                    {/* {lockYieldz} $VP */} {"0"}
                  </h4>
                </div>
              </div>
              <div className="flex flex-row py-3">
                <div className="align-middle border-[1px] rounded-lg bg-white/5  border-white/10 my-auto w-[60px] h-[60px] flex">
                  <Image
                    className="z-[-9999] top-0 right-0 m-auto"
                    src="./icon/Market Cap.svg"
                    alt="slider pannel"
                    width={32}
                    height={32}
                  />
                </div>
                <div className="m-auto ml-2">
                  <h4 className="text-white text-[20px] m-auto">My staked VPUMPY NFT 2</h4>
                  <h4 className="text-white font-semibold uppercase text-[24px] m-auto">
                    0
                  </h4>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default Dashboard;
