import React, { CSSProperties } from "react";
import Image from "next/image";
import GraButton, { TraButton } from "@/components/common/Buttons";
import { Fade } from "react-awesome-reveal";
import animation from "@/styles/animation.module.css";
import router from "next/router";
export interface MyCustomCSS extends CSSProperties {
  "--i": number;
}

interface Props { }

const CoinSection = (props: Props) => {
  return (
    <section className="sixth-panel items-center flex w-full z-2 relative">
      <div className="grow justify-center mx-10 md:items-center md:px-8 sm:px-4 px-0 w-[50%]">
        {/* <Fade triggerOnce direction="left" duration={3000}>
          <div className="flex justify-start w-2/3">
            <h2 className="lg:text-[50px] md:text-[40px] sm:text-[30px] text-[20px] text-white font-bold text-left">
              Take your first step <br></br>into the new vision of stable
              rewards!
            </h2>
          </div>

          <h2 className="md:text-[24px] text-[16px] text-[#898CA9] font-bold">
            Our system is a mutli-layer reward based optimisied economic model
            that uses the fees generated by the protocol in the most optimal
            way. Paying out the generated protocol fess to stakers through an
            ecosystem booster token(bYZ), which prevents inflation and
            distribute the rewards through a multi rewarding CORE + SHDW pool in
            connection with incorporate features, like governance system that
            allows bYZ holders to decide on important questions of the platform.
          </h2>
          <div>
            <GraButton className=" w-[156px] h-[56px] font-bold mt-10" onClick={()=>{router.push("https://yieldz.gitbook.io/yieldz-protocol/")}}>
              Learn more
            </GraButton>
          </div>
        </Fade> */}
      </div>
      <div className="flex-none justify-center w-[30%]  md:block hidden ">

      </div>
    </section>
  );
};

export default CoinSection;
